##############################
# ccRides Main Configuration #
##############################

# Please do not touch
confVersion: 7

# Settings about linking to other plugins
Integrations:
  vault: false
  placeholderAPI: false
  clearlag: false

# Commands Options
Commands:
  # Enable/Disable the player commands
  # If false, you can only join rides through signs,
  # or clicking their seats if they have JOIN_BY_CART enabled.
  enablePlayerCommands: true

# Permissions settings
Permissions:
  # whether each ride needs separate permissions,
  # if false then 'ccrides.user' grants access to all rides.
  # Per-Ride permissions in format 'ccrides.ride.[rideName]'
  perRidePermissions: false

# Ride Entities Settings
Entities:
  # Update the location of entities even when the ride isn't moving.
  # Please enable if parts of your rides move when the ride isn't in motion
  # Shouldn't be necessary for 1.12+
  forceUpdateLocations: false
  # How often to update these locations. in ticks.
  forceUpdateInterval: 1

# Other Ride settings
Rides:
  # Enable/Disable ride messages
  Messages:
    broadcastPaidPrice: true
    broadcastCountdown: true
    broadcastWaitingPlayers: true
    broadcastRideFull: true
    broadcastNoPermission: true
    broadcastNoFunds: true
    broadcastSeatTaken: true
  Operation:
    # Allow rides to start automatically after passing their 'START_PLAYERS' setting.
    enableAutoStart: true
    # Force Chunks containing a ride to stay loaded
    forceLoadChunks: false
    # Options for ride queues
    Queue:
      # Enable or disable queues completely
      enable: true
      # Enable the fast Queues - players who have 'fastPasses' will be able to join rides faster.
      # FastPasses are unlimited for players with 'ccrides.fastpass.unlimited' permission
      enableFastQueue: false
      # QUEUE PRIORITIES
      # For every x players in the fast queue, how many do we let in from the normal queue
      # The default (3 fast, 1 normal) means one rider is let in from the normal queue for every three in the fast queue.
      fastPriority: 3
      normalPriority: 1